version: '3.1'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_DB: birthdays
      POSTGRES_USER: restuser
      POSTGRES_PASSWORD: sql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
